create table public.sessions (
  id bigint generated by default as identity not null,
  user_id text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  total_volume numeric not null,
  exercises jsonb null,
  constraint sessions_pkey primary key (id)
) TABLESPACE pg_default;
create table public.nutrition (
  id bigint generated by default as identity not null,
  user_id text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  carbs numeric null,
  protein numeric null,
  fat numeric null,
  bcaa numeric null,
  creatine numeric null,
  glutamine numeric null,
  constraint nutrition_pkey primary key (id)
) TABLESPACE pg_default

